#!/bin/bash
#
# The MIT License
#
# Copyright (c) 2010 INQNET GmbH <oss@inqnet.at>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.


# find count(jobid) of all media which is used in Fullbackup jobs which does not belong to the Fullbackup pool
COUNT=`echo "SELECT count(DISTINCT j.jobid) FROM job j, jobmedia jm, media m, pool p WHERE j.jobid=jm.jobid AND jm.mediaid=m.mediaid AND m.poolid=p.poolid AND p.name NOT ilike '%full%' AND j.level='F' AND j.type='B' and j.jobstatus in ('T', 'e');" | psql bacula -1 -q -A -t`

if [[ $COUNT != "0" ]]; then
	if [[ $COUNT = "" ]]; then
		echo "Unable to read output from psql"
		exit 1
	fi
	echo "ERROR: $COUNT Full-Backup jobs use media from the wrong pool"
	exit 2;
else
	echo "OK: all Full-Backup jobs only use Fullbackup media"
	exit 0
fi



