#!/bin/bash
#
# The MIT License
#
# Copyright (c) 2010 INQNET GmbH <oss@inqnet.at>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.


INTERVAL='30 hours'

# finds all clients which did not get backed up in the last 48 hours
if [ "${1}" == "-v" ];then
	echo "select * from client where clientid not in (select clientid from job where endtime > (NOW() - INTERVAL '$INTERVAL') AND jobstatus = 'T');" | psql bacula -1 -q -A -t
fi
COUNT=`echo "select count(*) from client where clientid not in (select clientid from job where endtime > (NOW() - INTERVAL '$INTERVAL') AND jobstatus = 'T');" | psql bacula -1 -q -A -t`

if (( $COUNT > 5 )); then
#	if [[ $out = "" ]]; then
	if [[ $COUNT = "" ]]; then
		echo "Unable to read output from psql"
		exit 1
	fi
	echo "CRITICAL: $COUNT clients were not backed up in the last $INTERVAL"
	exit 2;
else
	echo "OK: all/most clients got backed up in the last $INTERVAL"
	exit 0
fi



