#!/bin/bash
#
# The MIT License
#
# Copyright (c) 2010 INQNET GmbH <oss@inqnet.at>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.


COUNT=`echo "SELECT COUNT(*) FROM Media WHERE (VolErrors>0) OR (VolStatus='Error') OR (VolStatus='Disabled')" | psql bacula -1 -q -A -t`

if [ "$1" == "-v" ];then
	echo "SELECT * FROM Media WHERE (VolErrors>0) OR (VolStatus='Error') OR (VolStatus='Disabled')" | psql bacula -1 -q -A -t
fi

if [[ $COUNT != "0" ]]; then
	if [[ $COUNT = "" ]]; then
		echo "Unable to read output from psql"
		exit 1
	fi
	echo "ERROR: $COUNT volumes with state 'Error' found"
	exit 2;
else
	echo "OK: no Volumes with state 'Error' found"
	exit 0
fi



