#!/usr/bin/perl
#
# (C) 2013, Clemens Schwaighofer
# currently only works with PostgreSQL DB and only with ONE catalog database

use strict;
use warnings;
use DBD::Pg;

# get the config data from the bacula dbcheck command
my $dir_conf='/usr/sbin/dbcheck -B -c /etc/bacula/bacula-dir.conf';
open(FP, "$dir_conf|") or die "Can't get catalog information $@";
my %cfg;
while (my $l = <FP>)
{
	if ($l =~ /(\w+)=(.+)/)
	{
		$cfg{$1} = $2;
	}
}
close(FP);
# set the db connect data, a) from enviroment (munin conf), local conf (bacula) or default
my $DBUSER = $ENV{DBUSER} || $cfg{'db_user'} || 'bacula';
my $DBPORT = $ENV{DBPORT} || $cfg{'db_port'} || '5432';
my $DBHOST = $ENV{DBHOST} || $cfg{'db_address'} || 'localhost';
my $DBNAME = $ENV{DBNAME} || $cfg{'db_name'} || 'bacula';
my $DBPASS = $ENV{DBPASS} || $cfg{'db_password'};

if (defined($ARGV[0]) and ($ARGV[0] eq 'config'))
{
	print "graph_title Clients Backuped\n";
	print "graph_args --lower-limit 0\n";
	print "graph_vlabel Number of clients\n";
	print "graph_category bacula\n";
	print "graph_info Backuped clients\n";

	print "clients.label Clients\n";

	exit(0);
}

# basic data and query vars
my $query;
my $cursor;
my $data;
# connect to DB
my $dsn = "DBI:Pg:dbname=".$DBNAME.";host=".$DBHOST.";port=".$DBPORT;
my $dbh = DBI->connect($dsn, $DBUSER, $DBPASS) || die ("Can't connect to db $DBNAME @ $DBHOST with user $DBUSER\n");

# bytes used by incremental backups
$query = "SELECT COUNT(*) AS iclients FROM client";
$cursor = $dbh->prepare(qq{$query}) || die ("Cannot prepare ".$DBI::errstr."\n");
$cursor->execute() || die ("Cannot execute ".$cursor->errstr."\n");
$data = $cursor->fetchrow_hashref;
my $ICLIENTS = $data->{'iclients'};

print "clients.value $ICLIENTS\n";

exit(0);
