#!/bin/sh
#
# The MIT License
# 
# Copyright (c) 2010 INQNET GmbH <oss@inqnet.at>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# available bytes
AVAIL=`echo "select numvols * maxvolbytes from pool where name='Default'" | psql --pset t bacula | sed -e 's/ //g'`;

if [ "$1" = "config" ]; then
	echo "graph_title Clients Backuped"
	echo "graph_args --lower-limit 0"
	echo 'graph_vlabel Number of clients'
	echo 'graph_category bacula'
	echo 'graph_info Backuped clients'

	echo 'clients.label Clients'

	exit 0
fi

# bytes used by incremental backups
ICLIENTS=`echo "select count(*) from client;" | psql --pset t bacula | sed -e 's/ //g'`;

echo "clients.value $ICLIENTS"

exit 0
