#!/bin/sh
#
# The MIT License
#
# Copyright (c) 2010 INQNET GmbH <oss@inqnet.at>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.


# available bytes
AVAIL=`echo "select numvols * maxvolbytes from pool where name='Default'" | psql --pset t bacula | sed -e 's/ //g'`;

if [ "$1" = "config" ]; then
	echo "graph_title Bytes consumed by backup levels"
	echo "graph_args --base 1024 --lower-limit 0"
	echo 'graph_vlabel Bytes'
	echo 'graph_category bacula'
	echo 'graph_info Bytes by backup level'
        echo 'graph_order incremental differential avail free'

	echo 'incremental.label Incremental'
	echo 'incremental.draw AREA'
	echo 'incremental.info Bytes used by incremental'

	echo 'differential.label Differntial'
	echo 'differential.draw STACK'
	echo 'differential.info Bytes used by differential backups'

	echo 'free.label Free'
	echo 'free.draw STACK'
	echo 'free.info Free bytes'

	echo 'avail.label Total pool size'
	echo 'avail.draw LINE1'
	echo 'avail.info Available bytes in backup pool'

	exit 0
fi

# bytes used by incremental backups
IBYTES=`echo "select sum(jobbytes) from job where level='I' and type='B'" | psql --pset t bacula | sed -e 's/ //g'`;
# bytes used by differential backups
DBYTES=`echo "select sum(jobbytes) from job where level='D' and type='B'" | psql --pset t bacula | sed -e 's/ //g'`;
# Free bytes
FREE=$(($AVAIL-$IBYTES-$DBYTES));


echo "avail.value $AVAIL"
echo "incremental.value $IBYTES"
echo "differential.value $DBYTES"
echo "free.value $FREE"

exit 0
